### ISSUE TITLE
Search + Autocomplete

### ISSUE THREAD

**Issue by skipjack** [gregvenech/webpack-design#1]
Moving this issue over from @patelsky's in [docs #75](https://github.com/webpack/docs/issues/75).

![Search Screenshot](https://cloud.githubusercontent.com/assets/8988697/17747185/a6617474-6481-11e6-9224-9528dad1b49c.png)

As I mentioned there I think this is a great idea but more of a phase 2 thing. Once we have the first iteration of the site squared away I think we can start looking into this. At that point we'd actually have content to search through 😄. We'd have to talk to @bebraw about how to auto generate the json to search through, maybe [Antwar](http://antwarjs.github.io/) can help us somehow there. Here's a slightly reformatted version of the schema @patelsky laid out:

``` JavaScript
{
  config: [
    {
      name:resolve,
      short_description: "Options affecting the resolving of modules",
      link: "https://webpack.github.io/docs/configuration.html#resolve"
      options: [
        {
          name: "alias"
          short_description: "When trying to “resolve a module path” the module name is matched to the resolve.alias option",
          link:"..."
        }
      ],
    },
    //...
  ],
  plugins: [{
    // ...
  }],
  api: [{
    //...
  }],
}
```

We should definitely get some feedback from the core team, @sokra, @jhnns, @bebraw, and @TheLarkInn, on this as well. In the meantime, we can definitely play around with the design. I like what you've done but I'd like to synchronize it a bit more with the other mockups. @patelsky you're welcome to fork the repo and create a "Search" mockup if you have time, if not I'll probably come back to this and start playing around it once we've finished some other things up (already have a few ideas).

**Comment by bebraw** [comment]
If we do something on our own, it would have to go through [lunr](http://lunrjs.com/). The technique is quite simple actually and I cover the rough idea [here](http://survivejs.com/webpack/advanced-techniques/understanding-chunks/).

Plenty of projects use [DocSearch](https://community.algolia.com/docsearch/) (algolia based). I have a feeling integrating that would take less effort than doing something custom on our own.

**Comment by joshed-io** [comment]
Nice design!

If you are open to trying a DocSearch solution, the [DocSearch scraper](https://github.com/algolia/docsearch-scraper) is open source now and it would be possible to add additional JSON to the records to produce that custom UI, which could then be built using [autocomplete.js](https://github.com/algolia/autocomplete.js) (or even [instantsearch.js](https://github.com/algolia/instantsearch.js) for something more immersive). Time would be saved by not having to do that custom content-to-JSON mapping step.

PS If you want to play with DocSearch live on the existing webpack docs you can pull [my fork down](https://github.com/dzello/docs/tree/add-docsearch) and fire it up locally on the `add-docsearch` branch. That will give you an idea of how DocSearch has indexed the content and a feel for the search UX.

**Comment by joshed-io** [comment]
Or, for an easier way to see it in action, just hit this [live version](http://dzello.com/docs/) I've deployed.

**Comment by skipjack** [comment]
@dzello yea whatever you and @bebraw decide on for indexing is fine with me. 

> Or, for an easier way to see it in action, just hit this live version I've deployed.

Looks good! My goal is to finish the search design for large and small screen sizes first, which will probably be a slightly simpler version of @patelsky's above. Then we can figure out whether to map it to our own components or customize it solely through CSS. I'll start playing around with the tools you've both mentioned.

**Comment by bebraw** [comment]
Maybe we could get something rough merged at first and go from there. No need to be perfect the first time around.

**Comment by skipjack** [comment]
@bebraw that's true, don't have to wait on the design to get the first iteration done. I just figured I'd try to at least get a rough design going while the content is still the main focus.

**Comment by jhnns** [comment]
Looking forward to it :)
